FROM node:14-alpine AS development

ENV NODE_ENV development

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
COPY frontend ./

EXPOSE 3000

CMD [ "npm", "start" ]
