FROM golang:1.19.5-alpine

RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY backend ./backend
RUN pwd && ls -la

RUN cd backend && CGO_ENABLED=0 GOOS=linux go build

EXPOSE 8080

CMD [ "/app/backend/backend" ]
